---
version: "3.8"
services:
  swag:
    extends:
      file: common-services.yaml
      service: production
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
       - NET_ADMIN
    environment:
       - DOCKER_MODS= #add a modfication to SWAG container. Separate multiple mods with |. See README for list of available mods.
       - PUID=33
       - PGID=33
       - URL=
       - VALIDATION=http
       - SUBDOMAINS= #optional
       - CERTPROVIDER= #optional
       - DNSPLUGIN= #optional - see README for information on DNS plugins
       - PROPAGATION= #optional
       - EMAIL= #optional - an email address is requied if you want to receieve certificate renewal notifications
       - ONLY_SUBDOMAINS=true #optional
       - EXTRA_DOMAINS= #optional
       - STAGING=false #optional
    volumes:
       - /your/local/config/path:/config #replace /your/local/config/path with the path to your local configuration
    ports:
       - 443:443
       - 80:80 #optional
  ldap-auth:
    extends:
      file: common-services.yaml
      service: production
    image: lscr.io/linuxserver/ldap-auth:latest
    container_name: ldap-auth
    environment:
      - DOCKER_MODS= #add a modfication to SWAG container. Separate multiple mods with |. See README for list of available mods.
      - FERNETKEY= #optional
      - CERTFILE= #optional
      - KEYFILE= #optional
    ports:
      - 8888:8888
      - 9000:9000
  db:
    extends:
      file: common-services.yaml
      service: production
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe #replace notSecureChangeMe with your own password
  phpmyadmin:
    extends:
      file: common-services.yaml
      service: production
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - DOCKER_MODS= #add a modfication to SWAG container. Separate multiple mods with |. See README for list of available mods.
      - PMA_ARBITRARY=1
